### ISSUE TITLE
Implement LDAP account creation and deletion

### ISSUE THREAD

**Issue by vranki** [TampereHacklab/mulysa#10] opened 2019-06-26 17:20 UTC
Listen to user activation signal, create or delete LDAP user if requested.

**Comment by tswfi** [comment] 2019-06-26 17:24
also disable ldap user if requested

**Comment by olmari** [comment] 2021-09-21 22:56
AFAIK indeed with OIDC/SSO-support implemented in Mulysa generally direct LDAP-integration is not really needed in Mulysa. if LDAP is _really_ wanted to be actual user database still, it can be set as SSO/Keycloak backend instead.

Though now as Mulysa can act as SSO-provider, the LDAP for user management is kinda surplus. though LDAP could still be usedwith computer/machine accounts where it was intended for).

**Comment by tswfi** [comment] 2021-09-22 07:03
yup, closing this.
if / when this is needed we can always open new issues for this.

**Closed by tswfi** 2021-09-22 07:03 UTC
Labels: enhancement
