### ISSUE TITLE
Limit max days of payment

### ISSUE THREAD

**Issue by vranki** [TampereHacklab/mulysa#131] opened 2020-03-01 17:09 UTC
Services can define maximum number of days it can be paid in advance. 

This is not handled yet in businesslogic. Add the implementation.

**Comment by vranki** [comment] 2020-03-03 20:09
Field in model now. Needs logic.

**Comment by tswfi** [comment] 2020-12-06 17:13
duplicate of #125

**Closed by tswfi** 2020-12-06 17:13 UTC
Labels: enhancement
